
{{- range $scenarioIdx, $scenarioName := $.Values.scenario }}
{{- $args := dict "scenarioName" $scenarioName "Values" $.Values }}
{{- range $officeIdx := until ( int ( include "smtc.noffices" $args ) ) }}
{{- $officeName := printf "%s-office%d" $scenarioName (add $officeIdx 1) }}
{{- $scope1 := printf "office%d-svc" (add $officeIdx 1) }}
{{- if contains $.Values.buildScope $scope1 }}

{{- if (int $.Values.otType) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $officeName }}-object-tracking
  labels:
     app: {{ $officeName }}-object-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $officeName }}-object-tracking
  template:
    metadata:
      labels:
        app: {{ $officeName }}-object-tracking
    spec:
      enableServiceLinks: false
      containers:
        - name: {{ $officeName }}-object-tracking
          image: {{ $.Values.registryPrefix }}smtc_object_tracking:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OFFICE
              {{- $args := dict "scenarioName" $scenarioName "Values" $.Values "officeIdx" $officeIdx }}
              value: {{ include "smtc.env.office" $args | quote }}
            - name: DBHOST
              {{- $args := dict "officeName" $officeName "Values" $.Values }}
              value: {{ include "smtc.env.dbhost" $args | quote }}
            - name: MQTTHOST
              value: "{{ $officeName }}-mqtt-service"
            - name: MQTT_TOPIC
              value: "relayanalytics"
            - name: SCENARIO
              value: {{ $scenarioName | quote }}
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
      volumes:
          - name: timezone
            hostPath:
                path: /etc/localtime
                type: File
      {{ include "smtc.platform.node-selector" $ }}

{{- end }}

---

{{- end }}
{{- end }}
{{- end }}
