
version: "3.7"

services:

    cloud_db:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.1
        ports:
            - target: 9300
              published: 9300
              protocol: tcp
              mode: host
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - cloud_esdata:/usr/share/elasticsearch/data:rw
        environment:
            - "cluster.name=db-cluster"
            - "node.name=cloud_db"
            - "node.master=true"
            - "node.data=false"
            - "transport.publish_host={{.Node.Hostname}}"
            - "transport.port=9300"
            - "action.auto_create_index=0"
            - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
            - "NO_PROXY=*"
            - "no_proxy=*"

    cloud_web:
        image: smtc_web_cloud:latest
        ports:
            - "443:8080"
        environment:
            DBHOST: "http://cloud_db:9200"
            NO_PROXY: "*"
            no_proxy: "*"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        secrets:
            - source: self_crt
              target: self.crt
              uid: ${USER_ID}
              gid: ${GROUP_ID}
              mode: 0444
            - source: self_key
              target: self.key
              uid: ${USER_ID}
              gid: ${GROUP_ID}
              mode: 0440
            - source: dhparam_pem
              target: dhparam.pem
              uid: ${USER_ID}
              gid: ${GROUP_ID}
              mode: 0444

secrets:
    self_key:
        file: ../../certificate/self.key
    self_crt:
        file: ../../certificate/self.crt
    dhparam_pem:
        file: ../../certificate/dhparam.pem

volumes:
    cloud_esdata:
        driver: local
