# smtc_api_gateway_tunnelled

FROM smtc_api_gateway
USER root

RUN  yum install -y -q openssh-clients && rm -rf /var/cache/yum/*
COPY *.sh /home/
CMD  ["/home/tunnel.sh","/home/gateway.py"]
WORKDIR /home

####
ARG UID
USER ${UID}
####

