# smtc_database_tunnelled

FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.1
RUN  yum install -y -q openssh-clients && rm -rf /var/cache/yum/*
COPY *.sh /home/
ENTRYPOINT ["/home/tunnel.sh","/usr/local/bin/docker-entrypoint.sh","eswrapper"]
WORKDIR /home

